export const RECIPESAURUS_BAD_REQUEST_CODE = 'RECIPESAURUS_BAD_REQUEST';
export const RECIPESAURUS_UNAUTHORIZED_CODE = 'RECIPESAURUS_UNAUTHORIZED';
export const RECIPESAURUS_FORBIDDEN_CODE = 'RECIPESAURUS_FORBIDDEN';
export const RECIPESAURUS_NOT_FOUND_CODE = 'RECIPESAURUS_NOT_FOUND';
export const RECIPESAURUS_PAYMENT_REQUIRED_CODE = 'RECIPESAURUS_PAYMENT_REQUIRED';
export const RECIPESAURUS_RATE_LIMITED_CODE = 'RECIPESAURUS_RATE_LIMITED';
export const RECIPESAURUS_PAYLOAD_TOO_LARGE_CODE = 'RECIPESAURUS_PAYLOAD_TOO_LARGE';
export const RECIPESAURUS_BAD_GATEWAY_CODE = 'RECIPESAURUS_BAD_GATEWAY';
export const RECIPESAURUS_UNAVAILABLE_CODE = 'RECIPESAURUS_UNAVAILABLE';
export const RECIPESAURUS_INTERNAL_ERROR_CODE = 'RECIPESAURUS_INTERNAL_ERROR';
export const RECIPESAURUS_ERROR_CODE = 'RECIPESAURUS_ERROR';

export function getDefaultRecipesaurusErrorCode(status: number): string {
  if (status === 400) return RECIPESAURUS_BAD_REQUEST_CODE;
  if (status === 401) return RECIPESAURUS_UNAUTHORIZED_CODE;
  if (status === 402) return RECIPESAURUS_PAYMENT_REQUIRED_CODE;
  if (status === 403) return RECIPESAURUS_FORBIDDEN_CODE;
  if (status === 404) return RECIPESAURUS_NOT_FOUND_CODE;
  if (status === 413) return RECIPESAURUS_PAYLOAD_TOO_LARGE_CODE;
  if (status === 429) return RECIPESAURUS_RATE_LIMITED_CODE;
  if (status === 502) return RECIPESAURUS_BAD_GATEWAY_CODE;
  if (status === 503) return RECIPESAURUS_UNAVAILABLE_CODE;
  if (status >= 500) return RECIPESAURUS_INTERNAL_ERROR_CODE;

  return RECIPESAURUS_ERROR_CODE;
}
