INSERT OR IGNORE INTO users (
  id,
  email,
  name,
  avatar_url,
  password_hash,
  password_salt,
  email_verified,
  created_at
) VALUES (
  'recipesaurus-public-recipes',
  'recipesaurus@recipesaurus.ai',
  'Recipesaurus',
  NULL,
  'recipesaurus-system-user',
  'recipesaurus-system-user',
  1,
  1760000000000
);

UPDATE users
SET name = 'Recipesaurus', email_verified = 1
WHERE email = 'recipesaurus@recipesaurus.ai';

DELETE FROM recipes
WHERE is_public = 1
  AND user_id = (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai')
  AND id BETWEEN 'recipesaurus-sample-041' AND 'recipesaurus-sample-240';

INSERT OR REPLACE INTO recipes (
  id,
  user_id,
  owner_id,
  title,
  description,
  ingredients,
  instructions,
  tags,
  image_url,
  source_url,
  prep_time,
  cook_time,
  servings,
  is_public,
  created_at
) VALUES
(
  'recipesaurus-sample-001',
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  'Soft Herb Omelette',
  'A tender, pale-gold omelette with small curds, melted gruyere, and fresh herbs folded through the center.',
  json_array(
    '3 large eggs, room temperature',
    '1 tablespoon unsalted butter, plus 1 teaspoon for finishing',
    '2 tablespoons finely grated gruyere or mild cheddar',
    '1 tablespoon minced chives',
    '1 tablespoon minced flat-leaf parsley',
    '1 teaspoon whole milk or cream',
    '1/8 teaspoon fine sea salt',
    'Pinch of white or black pepper',
    '1 teaspoon neutral oil if your pan needs help',
    'Mixed greens or toast, for serving'
  ),
  json_array(
    'Crack the eggs into a bowl with milk, salt, and pepper, then whisk until completely blended with no visible streaks of white.',
    'Warm an 8-inch nonstick skillet over medium-low heat for 1 minute, then add butter and let it foam without browning.',
    'Pour in the eggs and immediately stir in small circles with a silicone spatula while shaking the pan gently.',
    'When the eggs look softly scrambled but still glossy, stop stirring and spread them into an even layer.',
    'Scatter the cheese, chives, and parsley across the center third of the omelette.',
    'Tilt the pan and fold one edge toward the center, then roll the omelette onto a warm plate seam-side down.',
    'Rub the top with the remaining teaspoon of butter so it shines.',
    'Serve immediately with toast or lightly dressed greens.'
  ),
  json_array('breakfast', 'eggs', 'vegetarian', 'quick', 'classic', 'recipesaurus'),
  'https://commons.wikimedia.org/wiki/Special:FilePath/Perfect_French_Omelets.jpg',
  'https://commons.wikimedia.org/wiki/File:Perfect_French_Omelets.jpg',
  '8 mins',
  '4 mins',
  '1',
  1,
  1760000000001
),
(
  'recipesaurus-sample-002',
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  'Roasted Tomato Basil Pasta',
  'A bright weeknight pasta with blistered cherry tomatoes, garlic, olive oil, basil, and a light parmesan finish.',
  json_array(
    '12 ounces spaghetti or linguine',
    '1 1/2 pounds cherry tomatoes, halved if large',
    '4 garlic cloves, thinly sliced',
    '3 tablespoons extra-virgin olive oil',
    '1 tablespoon tomato paste',
    '1/2 teaspoon red pepper flakes, optional',
    '1 teaspoon fine sea salt, plus more for pasta water',
    '1/2 teaspoon freshly ground black pepper',
    '1/2 cup packed fresh basil leaves, torn',
    '1/3 cup finely grated parmesan, plus more for serving',
    '1 teaspoon lemon zest',
    '1 tablespoon lemon juice'
  ),
  json_array(
    'Heat oven to 425 F and bring a large pot of salted water to a boil.',
    'Toss tomatoes with olive oil, garlic, tomato paste, red pepper flakes, salt, and black pepper on a rimmed sheet pan.',
    'Roast for 18 to 22 minutes, stirring once, until the tomatoes collapse and their juices thicken at the edges.',
    'Boil pasta until just shy of al dente, then reserve 1 cup pasta water before draining.',
    'Scrape the roasted tomatoes and every bit of pan juice into the pasta pot.',
    'Add the drained pasta and 1/2 cup reserved pasta water, tossing over low heat until glossy.',
    'Fold in basil, parmesan, lemon zest, and lemon juice, adding more pasta water if needed.',
    'Serve hot with extra parmesan and a few fresh basil leaves.'
  ),
  json_array('dinner', 'pasta', 'vegetarian', 'tomato', 'weeknight', 'recipesaurus'),
  'https://commons.wikimedia.org/wiki/Special:FilePath/Spaghetti_with_a_minimalist_heirloom_tomato_and_basil_sauce.jpg',
  'https://commons.wikimedia.org/wiki/File:Spaghetti_with_a_minimalist_heirloom_tomato_and_basil_sauce.jpg',
  '15 mins',
  '25 mins',
  '4',
  1,
  1760000000002
),
(
  'recipesaurus-sample-003',
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  'Vegan Black Bean Tacos',
  'Corn tortillas filled with saucy black beans, crunchy cabbage, avocado, pico de gallo, and lime.',
  json_array(
    '8 small corn tortillas',
    '2 cans black beans, drained and rinsed',
    '1 tablespoon olive oil',
    '1/2 yellow onion, finely diced',
    '2 garlic cloves, minced',
    '1 teaspoon ground cumin',
    '1 teaspoon smoked paprika',
    '1/2 teaspoon dried oregano',
    '1/2 teaspoon kosher salt',
    '1/3 cup vegetable broth or water',
    '1 cup shredded red cabbage',
    '1 ripe avocado, sliced',
    '3/4 cup pico de gallo or diced tomato salsa',
    '1/4 cup chopped cilantro',
    'Lime wedges, for serving'
  ),
  json_array(
    'Warm oil in a skillet over medium heat, then cook onion for 4 minutes until translucent.',
    'Add garlic, cumin, smoked paprika, oregano, and salt, stirring for 30 seconds until fragrant.',
    'Add black beans and broth, then simmer for 6 to 8 minutes until the liquid thickens.',
    'Mash about one third of the beans with the back of a spoon to make the filling creamy while leaving texture.',
    'Warm tortillas one at a time in a dry skillet until flexible and lightly toasted.',
    'Fill each tortilla with the black bean mixture.',
    'Top with cabbage, avocado, pico de gallo, cilantro, and a squeeze of lime.',
    'Serve right away with extra lime wedges and hot sauce if desired.'
  ),
  json_array('dinner', 'vegan', 'black beans', 'tacos', 'quick', 'recipesaurus'),
  'https://commons.wikimedia.org/wiki/Special:FilePath/Vegetables_and_Black_Bean_Tacos_(7212559656).jpg',
  'https://commons.wikimedia.org/wiki/File:Vegetables_and_Black_Bean_Tacos_(7212559656).jpg',
  '15 mins',
  '15 mins',
  '4',
  1,
  1760000000003
),
(
  'recipesaurus-sample-004',
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  'Lemon Dill Baked Salmon',
  'Tender salmon baked with lemon, dill, garlic, and olive oil until just flaky.',
  json_array(
    '4 salmon fillets, 5 to 6 ounces each',
    '2 tablespoons extra-virgin olive oil',
    '1 tablespoon unsalted butter, melted',
    '2 garlic cloves, finely grated',
    '1 lemon, thinly sliced',
    '1 tablespoon fresh lemon juice',
    '1 teaspoon lemon zest',
    '2 tablespoons chopped fresh dill',
    '1 tablespoon chopped parsley',
    '3/4 teaspoon kosher salt',
    '1/2 teaspoon freshly ground black pepper',
    '1 pound small potatoes or green beans, optional side',
    'Lemon wedges, for serving'
  ),
  json_array(
    'Heat oven to 400 F and line a baking dish with parchment.',
    'Pat salmon dry and place the fillets skin-side down with a little space between each piece.',
    'Stir olive oil, melted butter, garlic, lemon juice, lemon zest, dill, parsley, salt, and pepper in a small bowl.',
    'Spoon the lemon herb mixture evenly over the salmon.',
    'Lay lemon slices over the top of each fillet.',
    'Bake for 10 to 14 minutes, depending on thickness, until the salmon flakes at the edges and reaches 125 to 130 F for medium.',
    'Rest for 3 minutes so the juices settle.',
    'Serve with lemon wedges and potatoes or green beans.'
  ),
  json_array('dinner', 'salmon', 'seafood', 'lemon', 'high-protein', 'recipesaurus'),
  'https://commons.wikimedia.org/wiki/Special:FilePath/Baked_salmon_with_dill_and_lemon.jpg',
  'https://commons.wikimedia.org/wiki/File:Baked_salmon_with_dill_and_lemon.jpg',
  '10 mins',
  '14 mins',
  '4',
  1,
  1760000000004
),
(
  'recipesaurus-sample-005',
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  'Hearty Lentil Vegetable Soup',
  'A cozy one-pot lentil soup with carrots, celery, tomatoes, greens, and a lemony finish.',
  json_array(
    '2 tablespoons olive oil',
    '1 yellow onion, diced',
    '2 carrots, diced',
    '2 celery stalks, diced',
    '3 garlic cloves, minced',
    '1 1/2 cups brown or green lentils, rinsed',
    '1 can diced tomatoes, 14.5 ounces',
    '6 cups vegetable broth',
    '1 bay leaf',
    '1 teaspoon ground cumin',
    '1/2 teaspoon smoked paprika',
    '1 teaspoon kosher salt, plus more to taste',
    '3 cups chopped kale or spinach',
    '1 tablespoon lemon juice',
    '2 tablespoons chopped parsley'
  ),
  json_array(
    'Warm olive oil in a large pot over medium heat.',
    'Add onion, carrots, and celery, then cook for 7 minutes until softened but not browned.',
    'Stir in garlic, cumin, smoked paprika, and salt for 1 minute.',
    'Add lentils, diced tomatoes, broth, and bay leaf.',
    'Bring to a boil, then reduce to a steady simmer.',
    'Cook uncovered for 28 to 35 minutes until the lentils are tender but not mushy.',
    'Remove the bay leaf and mash a ladleful of soup against the side of the pot for body.',
    'Stir in kale or spinach until wilted.',
    'Finish with lemon juice and parsley, then adjust salt before serving.'
  ),
  json_array('lunch', 'soup', 'vegan', 'lentils', 'make-ahead', 'recipesaurus'),
  'https://commons.wikimedia.org/wiki/Special:FilePath/Bowl_of_lentil_soup_with_green_and_red_lentils.jpg',
  'https://commons.wikimedia.org/wiki/File:Bowl_of_lentil_soup_with_green_and_red_lentils.jpg',
  '15 mins',
  '35 mins',
  '6',
  1,
  1760000000005
);

INSERT OR REPLACE INTO recipes (
  id,
  user_id,
  owner_id,
  title,
  description,
  ingredients,
  instructions,
  tags,
  image_url,
  source_url,
  prep_time,
  cook_time,
  servings,
  is_public,
  created_at
) VALUES
(
  'recipesaurus-sample-006',
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  'Classic Caesar Salad',
  'Crisp romaine tossed with a bright lemon-parmesan dressing, crunchy skillet croutons, and plenty of black pepper.',
  json_array(
    '2 large romaine hearts, washed and torn into bite-size pieces',
    '3 tablespoons extra-virgin olive oil',
    '2 tablespoons mayonnaise or pasteurized egg yolk',
    '2 anchovy fillets, minced, or 1 teaspoon capers',
    '1 small garlic clove, finely grated',
    '1 tablespoon fresh lemon juice',
    '1 teaspoon Dijon mustard',
    '1/2 teaspoon Worcestershire sauce',
    '1/2 cup finely grated parmesan, divided',
    '2 cups rustic bread cubes',
    '1 tablespoon unsalted butter or olive oil for croutons',
    '1/4 teaspoon kosher salt',
    'Freshly ground black pepper'
  ),
  json_array(
    'Dry the romaine very well so the dressing clings instead of sliding off.',
    'Warm butter or olive oil in a skillet over medium heat, then toast the bread cubes for 5 to 7 minutes until crisp and golden.',
    'Whisk mayonnaise, anchovy or capers, garlic, lemon juice, Dijon, Worcestershire, salt, and several grinds of pepper in a large bowl.',
    'Slowly whisk in the olive oil until the dressing looks creamy and glossy.',
    'Add half of the parmesan and whisk again, tasting for lemon and salt.',
    'Add romaine to the bowl and toss with clean hands until every leaf is lightly coated.',
    'Fold in the croutons and remaining parmesan.',
    'Serve immediately with extra black pepper on top.'
  ),
  json_array('lunch', 'salad', 'classic', 'romaine', 'quick', 'recipesaurus'),
  'https://commons.wikimedia.org/wiki/Special:FilePath/Caesar_Salad.jpg',
  'https://commons.wikimedia.org/wiki/File:Caesar_Salad.jpg',
  '15 mins',
  '7 mins',
  '4',
  1,
  1760000000006
),
(
  'recipesaurus-sample-007',
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  'Mushroom Risotto',
  'Creamy arborio rice with browned mushrooms, parmesan, thyme, and a glossy butter finish.',
  json_array(
    '1 1/2 cups arborio rice',
    '10 ounces cremini mushrooms, sliced',
    '4 cups low-sodium vegetable or chicken broth',
    '1 small yellow onion, finely diced',
    '2 garlic cloves, minced',
    '1/2 cup dry white wine or extra broth',
    '2 tablespoons olive oil',
    '3 tablespoons unsalted butter, divided',
    '1/2 cup finely grated parmesan',
    '1 teaspoon fresh thyme leaves',
    '1/2 teaspoon kosher salt, plus more to taste',
    '1/2 teaspoon freshly ground black pepper',
    '2 tablespoons chopped parsley'
  ),
  json_array(
    'Bring the broth to a gentle simmer in a small saucepan and keep it warm.',
    'Heat olive oil in a wide pan, then brown the mushrooms in a single layer until their edges are golden.',
    'Transfer mushrooms to a plate and melt 1 tablespoon butter in the same pan.',
    'Cook onion for 4 minutes, then stir in garlic and thyme for 30 seconds.',
    'Add arborio rice and stir for 2 minutes until the grains look lightly translucent at the edges.',
    'Pour in wine and stir until almost fully absorbed.',
    'Add warm broth 1 ladle at a time, stirring often and waiting until each addition is absorbed before adding the next.',
    'When the rice is tender and creamy, fold in mushrooms, parmesan, remaining butter, parsley, salt, and pepper.'
  ),
  json_array('dinner', 'risotto', 'mushrooms', 'vegetarian', 'comfort food', 'recipesaurus'),
  'https://commons.wikimedia.org/wiki/Special:FilePath/Mushroom_Risotto_(4789409441).jpg',
  'https://commons.wikimedia.org/wiki/File:Mushroom_Risotto_(4789409441).jpg',
  '15 mins',
  '35 mins',
  '4',
  1,
  1760000000007
),
(
  'recipesaurus-sample-008',
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  'Margherita Pizza',
  'A simple blistered pizza with crushed tomato, fresh mozzarella, basil, olive oil, and a crisp-tender crust.',
  json_array(
    '1 pound pizza dough, room temperature',
    '1/3 cup crushed tomatoes',
    '1 small garlic clove, finely grated',
    '1 tablespoon extra-virgin olive oil, plus more for drizzling',
    '1/2 teaspoon kosher salt',
    '6 ounces fresh mozzarella, torn and patted dry',
    '1/4 cup fresh basil leaves',
    '2 tablespoons finely grated parmesan, optional',
    '1 tablespoon semolina flour or cornmeal for the peel',
    'Pinch of red pepper flakes, optional',
    'All-purpose flour for shaping'
  ),
  json_array(
    'Heat oven to 500 F with a pizza stone or heavy sheet pan inside for at least 30 minutes.',
    'Stir crushed tomatoes, garlic, olive oil, salt, and red pepper flakes in a small bowl.',
    'Stretch the dough on a floured surface into a 12-inch round, leaving a slightly thicker rim.',
    'Dust a peel or inverted sheet pan with semolina, then transfer the dough to it.',
    'Spread a thin layer of tomato sauce over the dough, leaving the rim uncovered.',
    'Add torn mozzarella and a light sprinkle of parmesan if using.',
    'Slide the pizza onto the hot stone and bake for 8 to 11 minutes until the crust is blistered and the cheese bubbles.',
    'Top with basil and a drizzle of olive oil before slicing.'
  ),
  json_array('dinner', 'pizza', 'vegetarian', 'tomato', 'basil', 'recipesaurus'),
  'https://commons.wikimedia.org/wiki/Special:FilePath/Pizza_Margherita_01.jpg',
  'https://commons.wikimedia.org/wiki/File:Pizza_Margherita_01.jpg',
  '20 mins',
  '11 mins',
  '3',
  1,
  1760000000008
),
(
  'recipesaurus-sample-009',
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  'Banana Walnut Bread',
  'Moist banana bread with toasted walnuts, brown sugar, vanilla, and a soft cinnamon crumb.',
  json_array(
    '3 very ripe bananas, mashed',
    '1 3/4 cups all-purpose flour',
    '3/4 cup packed light brown sugar',
    '1 teaspoon baking soda',
    '1/2 teaspoon fine sea salt',
    '1/2 teaspoon ground cinnamon',
    '2 large eggs, room temperature',
    '1/2 cup unsalted butter, melted and cooled',
    '1/3 cup plain yogurt or sour cream',
    '1 teaspoon vanilla extract',
    '3/4 cup chopped walnuts, toasted',
    '1 tablespoon turbinado sugar, optional'
  ),
  json_array(
    'Heat oven to 350 F and line a 9-by-5-inch loaf pan with parchment.',
    'Mash bananas in a large bowl until mostly smooth with a few small pieces left for texture.',
    'Whisk in brown sugar, eggs, melted butter, yogurt, and vanilla.',
    'In a second bowl, whisk flour, baking soda, salt, and cinnamon.',
    'Fold the dry ingredients into the banana mixture just until no flour streaks remain.',
    'Fold in toasted walnuts, then scrape the batter into the prepared pan.',
    'Sprinkle turbinado sugar over the top if using.',
    'Bake for 55 to 65 minutes until a toothpick inserted in the center comes out clean, then cool before slicing.'
  ),
  json_array('breakfast', 'baking', 'banana', 'walnuts', 'make-ahead', 'recipesaurus'),
  'https://commons.wikimedia.org/wiki/Special:FilePath/Banana_bread_001.jpg',
  'https://commons.wikimedia.org/wiki/File:Banana_bread_001.jpg',
  '15 mins',
  '1 hr',
  '10',
  1,
  1760000000009
),
(
  'recipesaurus-sample-010',
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  'Beef and Broccoli Stir-Fry',
  'Tender strips of beef, crisp broccoli, garlic, ginger, and a glossy savory sauce served over rice.',
  json_array(
    '1 pound flank steak, thinly sliced across the grain',
    '1 pound broccoli florets',
    '3 tablespoons soy sauce, divided',
    '2 tablespoons oyster sauce',
    '1 tablespoon rice vinegar',
    '1 tablespoon brown sugar',
    '2 teaspoons cornstarch, divided',
    '2 garlic cloves, minced',
    '1 tablespoon fresh ginger, minced',
    '1 tablespoon toasted sesame oil',
    '2 tablespoons neutral oil',
    '1/3 cup water or beef broth',
    '2 scallions, sliced',
    'Cooked rice, for serving'
  ),
  json_array(
    'Toss sliced beef with 1 tablespoon soy sauce, 1 teaspoon cornstarch, and sesame oil, then let it stand for 10 minutes.',
    'Whisk remaining soy sauce, oyster sauce, rice vinegar, brown sugar, remaining cornstarch, and water in a small bowl.',
    'Steam or blanch broccoli for 2 minutes until bright green and still crisp.',
    'Heat a wok or large skillet over high heat and add 1 tablespoon neutral oil.',
    'Sear beef in a single layer for 1 to 2 minutes per side, then transfer to a plate.',
    'Add remaining oil, garlic, and ginger to the pan and stir for 20 seconds.',
    'Return broccoli and beef to the pan, pour in the sauce, and toss until glossy and thickened.',
    'Finish with scallions and serve over hot rice.'
  ),
  json_array('dinner', 'beef', 'broccoli', 'stir-fry', 'weeknight', 'recipesaurus'),
  'https://commons.wikimedia.org/wiki/Special:FilePath/Beef_and_broccoli_stir_fry.jpg',
  'https://commons.wikimedia.org/wiki/File:Beef_and_broccoli_stir_fry.jpg',
  '20 mins',
  '12 mins',
  '4',
  1,
  1760000000010
),
(
  'recipesaurus-sample-011',
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  'Chicken Noodle Soup',
  'A clear, cozy soup with tender chicken, egg noodles, carrots, celery, parsley, and lemon.',
  json_array(
    '1 1/4 pounds boneless skinless chicken thighs',
    '2 tablespoons olive oil',
    '1 yellow onion, diced',
    '3 carrots, sliced',
    '3 celery stalks, sliced',
    '3 garlic cloves, minced',
    '8 cups low-sodium chicken broth',
    '1 bay leaf',
    '1 teaspoon dried thyme',
    '6 ounces egg noodles',
    '2 tablespoons chopped parsley',
    '1 tablespoon lemon juice',
    '1 teaspoon kosher salt, plus more to taste',
    '1/2 teaspoon freshly ground black pepper'
  ),
  json_array(
    'Warm olive oil in a large pot over medium heat.',
    'Cook onion, carrots, and celery for 6 minutes until the onion softens.',
    'Stir in garlic, thyme, salt, and pepper for 30 seconds.',
    'Add chicken thighs, broth, and bay leaf, then bring to a gentle boil.',
    'Reduce heat and simmer for 20 minutes until the chicken is cooked through.',
    'Transfer chicken to a board, shred it with two forks, and return it to the pot.',
    'Add egg noodles and simmer until tender, usually 6 to 8 minutes.',
    'Discard the bay leaf, then finish with parsley, lemon juice, and more salt if needed.'
  ),
  json_array('lunch', 'soup', 'chicken', 'noodles', 'comfort food', 'recipesaurus'),
  'https://commons.wikimedia.org/wiki/Special:FilePath/Chicken_noodle_soup.jpg',
  'https://commons.wikimedia.org/wiki/File:Chicken_noodle_soup.jpg',
  '15 mins',
  '35 mins',
  '6',
  1,
  1760000000011
),
(
  'recipesaurus-sample-012',
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  'Quinoa Stuffed Peppers',
  'Sweet bell peppers baked with a hearty quinoa, black bean, corn, tomato, and cheese filling.',
  json_array(
    '4 large bell peppers, halved lengthwise and seeded',
    '1 cup cooked quinoa',
    '1 can black beans, drained and rinsed',
    '1 cup corn kernels',
    '1 cup diced tomatoes, drained',
    '1/2 yellow onion, diced',
    '2 garlic cloves, minced',
    '1 teaspoon ground cumin',
    '1 teaspoon smoked paprika',
    '1/2 teaspoon kosher salt',
    '1 cup shredded Monterey Jack or cheddar',
    '2 tablespoons chopped cilantro',
    '1 tablespoon lime juice'
  ),
  json_array(
    'Heat oven to 400 F and lightly oil a baking dish.',
    'Place pepper halves cut-side up in the dish and season them with a pinch of salt.',
    'Cook onion in a skillet over medium heat for 4 minutes, then add garlic, cumin, and smoked paprika.',
    'Stir in quinoa, black beans, corn, tomatoes, and salt until warmed through.',
    'Remove from heat and fold in half of the cheese, cilantro, and lime juice.',
    'Spoon the filling into the pepper halves and cover the dish with foil.',
    'Bake for 25 minutes, then uncover and sprinkle with the remaining cheese.',
    'Bake 8 to 10 minutes more until the peppers are tender and the cheese is melted.'
  ),
  json_array('dinner', 'vegetarian', 'quinoa', 'peppers', 'make-ahead', 'recipesaurus'),
  'https://commons.wikimedia.org/wiki/Special:FilePath/Stuffed_Peppers_(4167895675).jpg',
  'https://commons.wikimedia.org/wiki/File:Stuffed_Peppers_(4167895675).jpg',
  '20 mins',
  '35 mins',
  '4',
  1,
  1760000000012
),
(
  'recipesaurus-sample-013',
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  'Weeknight Beef and Bean Chili',
  'A rich, gently smoky chili with ground beef, two kinds of beans, tomatoes, and warm spices.',
  json_array(
    '1 pound ground beef',
    '1 tablespoon olive oil',
    '1 yellow onion, diced',
    '1 red bell pepper, diced',
    '3 garlic cloves, minced',
    '2 tablespoons chili powder',
    '1 teaspoon ground cumin',
    '1 teaspoon smoked paprika',
    '1/2 teaspoon dried oregano',
    '1 can crushed tomatoes, 28 ounces',
    '1 can kidney beans, drained and rinsed',
    '1 can black beans, drained and rinsed',
    '1 cup beef broth',
    '1 teaspoon kosher salt',
    'Sour cream, scallions, or cheddar for serving'
  ),
  json_array(
    'Warm olive oil in a Dutch oven over medium-high heat.',
    'Brown the beef, breaking it into small pieces, until no pink remains.',
    'Add onion and bell pepper, then cook for 5 minutes until softened.',
    'Stir in garlic, chili powder, cumin, smoked paprika, oregano, and salt for 1 minute.',
    'Add crushed tomatoes, kidney beans, black beans, and beef broth.',
    'Bring to a boil, then reduce to a steady simmer.',
    'Cook uncovered for 25 to 30 minutes, stirring occasionally, until thick and rich.',
    'Serve with sour cream, scallions, or cheddar if desired.'
  ),
  json_array('dinner', 'chili', 'beef', 'beans', 'one-pot', 'recipesaurus'),
  'https://commons.wikimedia.org/wiki/Special:FilePath/Chili_con_carne_1.jpg',
  'https://commons.wikimedia.org/wiki/File:Chili_con_carne_1.jpg',
  '15 mins',
  '35 mins',
  '6',
  1,
  1760000000013
),
(
  'recipesaurus-sample-014',
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  'Greek Yogurt Berry Parfait',
  'Creamy yogurt layered with juicy berries, crunchy granola, honey, lemon zest, and almonds.',
  json_array(
    '2 cups plain Greek yogurt',
    '1 cup strawberries, sliced',
    '1 cup blueberries',
    '1 cup raspberries or blackberries',
    '1 cup granola',
    '2 tablespoons honey, plus more to taste',
    '1 teaspoon vanilla extract',
    '1 teaspoon lemon zest',
    '1 tablespoon chia seeds',
    '1/4 cup sliced almonds, toasted',
    'Pinch of fine sea salt',
    'Fresh mint leaves, optional'
  ),
  json_array(
    'Stir Greek yogurt with vanilla, a pinch of salt, and 1 tablespoon honey.',
    'Toss the berries with lemon zest and the remaining tablespoon of honey.',
    'Let the berries stand for 5 minutes so they become juicy.',
    'Spoon a layer of yogurt into each glass or jar.',
    'Add a layer of berries, then a layer of granola.',
    'Repeat the layers until the glasses are full.',
    'Top with chia seeds, toasted almonds, and mint if using.',
    'Serve right away for crunch or chill up to 2 hours for a softer parfait.'
  ),
  json_array('breakfast', 'yogurt', 'berries', 'no-cook', 'quick', 'recipesaurus'),
  'https://commons.wikimedia.org/wiki/Special:FilePath/Yogurt_parfait.jpg',
  'https://commons.wikimedia.org/wiki/File:Yogurt_parfait.jpg',
  '12 mins',
  '0 mins',
  '4',
  1,
  1760000000014
),
(
  'recipesaurus-sample-015',
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  'Shrimp Fried Rice',
  'Cold rice stir-fried with shrimp, eggs, peas, carrots, scallions, soy sauce, and sesame oil.',
  json_array(
    '4 cups cold cooked jasmine rice',
    '12 ounces peeled deveined shrimp',
    '2 large eggs, beaten',
    '1 cup frozen peas and carrots',
    '3 scallions, sliced',
    '2 garlic cloves, minced',
    '1 teaspoon fresh ginger, minced',
    '3 tablespoons soy sauce',
    '1 tablespoon oyster sauce or hoisin sauce',
    '2 teaspoons toasted sesame oil',
    '2 tablespoons neutral oil',
    '1/2 teaspoon white pepper or black pepper',
    'Lime wedges, for serving'
  ),
  json_array(
    'Pat shrimp dry and season lightly with pepper.',
    'Heat 1 tablespoon neutral oil in a wok or large skillet over high heat.',
    'Cook shrimp for 1 to 2 minutes per side until pink, then transfer to a plate.',
    'Add beaten eggs to the pan, scramble softly, and move them to the plate with the shrimp.',
    'Add remaining oil, garlic, ginger, and the white parts of the scallions for 30 seconds.',
    'Add cold rice and peas and carrots, breaking up clumps as the rice heats.',
    'Return shrimp and eggs to the pan with soy sauce, oyster sauce, and sesame oil.',
    'Toss until everything is hot, then finish with scallion greens and lime wedges.'
  ),
  json_array('dinner', 'shrimp', 'rice', 'stir-fry', 'quick', 'recipesaurus'),
  'https://commons.wikimedia.org/wiki/Special:FilePath/Shrimp_Fried_Rice_(Taiwan).jpg',
  'https://commons.wikimedia.org/wiki/File:Shrimp_Fried_Rice_(Taiwan).jpg',
  '15 mins',
  '12 mins',
  '4',
  1,
  1760000000015
),
(
  'recipesaurus-sample-016',
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  'Buttermilk Pancakes',
  'Tall, tender pancakes with crisp edges, a lightly tangy crumb, butter, and warm syrup.',
  json_array(
    '1 1/2 cups all-purpose flour',
    '2 tablespoons granulated sugar',
    '2 teaspoons baking powder',
    '1/2 teaspoon baking soda',
    '1/2 teaspoon fine sea salt',
    '1 1/4 cups buttermilk',
    '2 large eggs',
    '3 tablespoons unsalted butter, melted and cooled',
    '1 teaspoon vanilla extract',
    '1 tablespoon neutral oil or butter for the pan',
    'Maple syrup or honey, for serving',
    'Fresh berries, optional'
  ),
  json_array(
    'Whisk flour, sugar, baking powder, baking soda, and salt in a large bowl.',
    'Whisk buttermilk, eggs, melted butter, and vanilla in a second bowl.',
    'Pour wet ingredients into dry ingredients and stir gently until just combined.',
    'Rest the batter for 10 minutes while a griddle heats over medium.',
    'Lightly grease the griddle with oil or butter.',
    'Scoop 1/4 cup batter per pancake and cook until bubbles form and the edges look set.',
    'Flip once and cook 1 to 2 minutes more until golden and cooked through.',
    'Serve warm with syrup or honey and berries if desired.'
  ),
  json_array('breakfast', 'pancakes', 'vegetarian', 'brunch', 'classic', 'recipesaurus'),
  'https://commons.wikimedia.org/wiki/Special:FilePath/Pancake_stack_with_honey.jpg',
  'https://commons.wikimedia.org/wiki/File:Pancake_stack_with_honey.jpg',
  '15 mins',
  '15 mins',
  '4',
  1,
  1760000000016
),
(
  'recipesaurus-sample-017',
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  'Caprese Salad',
  'Ripe tomatoes, fresh mozzarella, basil, olive oil, flaky salt, and a light balsamic finish.',
  json_array(
    '4 ripe tomatoes, sliced',
    '12 ounces fresh mozzarella, sliced',
    '1 cup fresh basil leaves',
    '3 tablespoons extra-virgin olive oil',
    '1 tablespoon balsamic vinegar or glaze',
    '1/2 teaspoon flaky sea salt',
    '1/2 teaspoon freshly ground black pepper',
    '1 teaspoon lemon zest, optional',
    'Pinch of crushed red pepper, optional',
    '2 tablespoons toasted pine nuts, optional',
    'Crusty bread, for serving'
  ),
  json_array(
    'Choose tomatoes that smell sweet and feel heavy for their size.',
    'Slice tomatoes and mozzarella into similar thicknesses for even bites.',
    'Season the tomato slices lightly with flaky salt and let them stand for 5 minutes.',
    'Arrange tomatoes and mozzarella on a platter, overlapping the slices.',
    'Tuck basil leaves between the layers.',
    'Drizzle with olive oil and a small amount of balsamic vinegar or glaze.',
    'Finish with black pepper, lemon zest, crushed red pepper, and pine nuts if using.',
    'Serve at room temperature with crusty bread.'
  ),
  json_array('salad', 'vegetarian', 'tomato', 'mozzarella', 'no-cook', 'recipesaurus'),
  'https://commons.wikimedia.org/wiki/Special:FilePath/Insalata_caprese.jpg',
  'https://commons.wikimedia.org/wiki/File:Insalata_caprese.jpg',
  '15 mins',
  '0 mins',
  '4',
  1,
  1760000000017
),
(
  'recipesaurus-sample-018',
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  'Sesame Noodle Salad',
  'Chilled noodles tossed with crunchy vegetables, edamame, herbs, sesame, and a ginger-soy dressing.',
  json_array(
    '8 ounces soba or thin wheat noodles',
    '1 cup shelled edamame',
    '1 English cucumber, julienned',
    '2 carrots, julienned',
    '1 red bell pepper, thinly sliced',
    '3 scallions, sliced',
    '1/2 cup chopped cilantro or mint',
    '2 tablespoons toasted sesame seeds',
    '3 tablespoons soy sauce',
    '2 tablespoons rice vinegar',
    '1 tablespoon toasted sesame oil',
    '1 tablespoon peanut butter or tahini',
    '1 teaspoon grated fresh ginger',
    '1 teaspoon honey or maple syrup'
  ),
  json_array(
    'Cook noodles according to package directions until just tender.',
    'Add edamame during the last minute of cooking, then drain everything together.',
    'Rinse noodles and edamame under cold water until fully chilled.',
    'Whisk soy sauce, rice vinegar, sesame oil, peanut butter or tahini, ginger, and honey in a large bowl.',
    'Add noodles and edamame to the dressing and toss until coated.',
    'Fold in cucumber, carrots, bell pepper, scallions, herbs, and sesame seeds.',
    'Let the salad stand for 10 minutes so the noodles absorb some dressing.',
    'Toss again before serving, adding a splash of water if the noodles tighten up.'
  ),
  json_array('lunch', 'noodles', 'vegetarian', 'salad', 'make-ahead', 'recipesaurus'),
  'https://commons.wikimedia.org/wiki/Special:FilePath/Noodlesalad1.jpg',
  'https://commons.wikimedia.org/wiki/File:Noodlesalad1.jpg',
  '20 mins',
  '8 mins',
  '4',
  1,
  1760000000018
),
(
  'recipesaurus-sample-019',
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  'Baked Mac and Cheese',
  'Creamy elbow macaroni in a cheddar-gruyere sauce with a crisp parmesan breadcrumb topping.',
  json_array(
    '12 ounces elbow macaroni',
    '4 tablespoons unsalted butter, divided',
    '1/4 cup all-purpose flour',
    '2 1/2 cups whole milk',
    '1/2 cup heavy cream',
    '2 cups shredded sharp cheddar',
    '1 cup shredded gruyere',
    '1 teaspoon Dijon mustard',
    '1/2 teaspoon smoked paprika',
    '1/2 teaspoon garlic powder',
    '1 cup panko breadcrumbs',
    '1/4 cup grated parmesan',
    '1 teaspoon kosher salt',
    '1/2 teaspoon black pepper'
  ),
  json_array(
    'Heat oven to 375 F and butter a 2-quart baking dish.',
    'Boil macaroni 1 minute less than the package directions, then drain.',
    'Melt 3 tablespoons butter in a saucepan and whisk in flour for 1 minute.',
    'Slowly whisk in milk and cream, then simmer until the sauce lightly thickens.',
    'Stir in cheddar, gruyere, Dijon, smoked paprika, garlic powder, salt, and pepper.',
    'Fold macaroni into the cheese sauce and transfer it to the baking dish.',
    'Melt remaining butter and mix with panko and parmesan, then scatter over the pasta.',
    'Bake for 20 to 25 minutes until bubbling at the edges and golden on top.'
  ),
  json_array('dinner', 'pasta', 'cheese', 'baked', 'comfort food', 'recipesaurus'),
  'https://commons.wikimedia.org/wiki/Special:FilePath/Baked_macaroni_and_cheese_close-up.jpg',
  'https://commons.wikimedia.org/wiki/File:Baked_macaroni_and_cheese_close-up.jpg',
  '15 mins',
  '30 mins',
  '6',
  1,
  1760000000019
),
(
  'recipesaurus-sample-020',
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  'Quinoa Chickpea Power Bowl',
  'A colorful vegan bowl with quinoa, chickpeas, roasted sweet potato, avocado, vegetables, and lemon tahini sauce.',
  json_array(
    '1 cup dry quinoa, rinsed',
    '1 can chickpeas, drained and rinsed',
    '1 medium sweet potato, diced',
    '2 tablespoons olive oil, divided',
    '1 teaspoon ground cumin',
    '1/2 teaspoon smoked paprika',
    '2 cups baby spinach',
    '1 cup cherry tomatoes, halved',
    '1 cucumber, diced',
    '1 avocado, sliced',
    '1/4 cup tahini',
    '2 tablespoons lemon juice',
    '1 small garlic clove, grated',
    '2 tablespoons chopped parsley',
    '2 tablespoons pumpkin seeds'
  ),
  json_array(
    'Heat oven to 425 F and line a sheet pan with parchment.',
    'Toss sweet potato and chickpeas with 1 tablespoon olive oil, cumin, smoked paprika, and salt.',
    'Roast for 22 to 25 minutes until the sweet potato is tender and the chickpeas are lightly crisp.',
    'Cook quinoa in 2 cups water until tender, then fluff with a fork.',
    'Whisk tahini, lemon juice, garlic, remaining olive oil, and enough water to make a pourable sauce.',
    'Divide spinach and quinoa among bowls.',
    'Top with roasted sweet potato, chickpeas, tomatoes, cucumber, avocado, parsley, and pumpkin seeds.',
    'Drizzle with lemon tahini sauce just before serving.'
  ),
  json_array('lunch', 'vegan', 'quinoa', 'chickpeas', 'bowl', 'recipesaurus'),
  'https://commons.wikimedia.org/wiki/Special:FilePath/Vegan_Quinoa_Bowl_(44040185371).jpg',
  'https://commons.wikimedia.org/wiki/File:Vegan_Quinoa_Bowl_(44040185371).jpg',
  '20 mins',
  '25 mins',
  '4',
  1,
  1760000000020
),
(
  'recipesaurus-sample-021',
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  'Herb Roasted Pork Loin',
  'Juicy pork loin roasted with Dijon, garlic, rosemary, thyme, shallots, and a simple pan sauce.',
  json_array(
    '2 1/2 pounds boneless pork loin',
    '2 tablespoons olive oil',
    '1 tablespoon Dijon mustard',
    '3 garlic cloves, minced',
    '1 tablespoon chopped fresh rosemary',
    '1 tablespoon chopped fresh thyme',
    '1 teaspoon kosher salt',
    '1/2 teaspoon freshly ground black pepper',
    '1/2 teaspoon crushed fennel seeds, optional',
    '3 shallots, halved',
    '2 carrots, cut into chunks',
    '1/2 cup chicken broth',
    '1/2 cup apple cider or unsweetened apple juice'
  ),
  json_array(
    'Heat oven to 375 F and pat the pork loin very dry.',
    'Mix olive oil, Dijon, garlic, rosemary, thyme, salt, pepper, and fennel seeds into a paste.',
    'Rub the herb paste all over the pork.',
    'Arrange shallots and carrots in a roasting pan and set the pork on top.',
    'Roast for 35 minutes, then pour broth and apple cider into the pan.',
    'Continue roasting until the center of the pork reaches 145 F, about 15 to 25 minutes more.',
    'Rest the pork for 10 minutes before slicing.',
    'Spoon the pan juices and roasted vegetables over the slices.'
  ),
  json_array('dinner', 'pork', 'roast', 'herbs', 'high-protein', 'recipesaurus'),
  'https://commons.wikimedia.org/wiki/Special:FilePath/Roasted_Loin_of_Pork_(2287948470).jpg',
  'https://commons.wikimedia.org/wiki/File:Roasted_Loin_of_Pork_(2287948470).jpg',
  '15 mins',
  '1 hr',
  '6',
  1,
  1760000000021
),
(
  'recipesaurus-sample-022',
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  'Vegetable Lasagna',
  'Layers of pasta, marinara, ricotta, spinach, zucchini, mushrooms, mozzarella, and parmesan baked until bubbling.',
  json_array(
    '12 lasagna noodles',
    '2 tablespoons olive oil',
    '1 zucchini, diced',
    '8 ounces mushrooms, sliced',
    '3 cups baby spinach',
    '2 garlic cloves, minced',
    '3 cups marinara sauce',
    '15 ounces ricotta cheese',
    '1 large egg',
    '2 cups shredded mozzarella',
    '1/2 cup grated parmesan',
    '1/4 cup chopped basil',
    '1 teaspoon kosher salt',
    '1/2 teaspoon black pepper'
  ),
  json_array(
    'Heat oven to 375 F and cook lasagna noodles until just flexible.',
    'Warm olive oil in a skillet and cook zucchini and mushrooms until their moisture evaporates.',
    'Stir in spinach and garlic until the spinach wilts, then season with salt and pepper.',
    'Mix ricotta, egg, basil, half of the parmesan, and a pinch of salt in a bowl.',
    'Spread a thin layer of marinara in a 9-by-13-inch baking dish.',
    'Layer noodles, ricotta mixture, vegetables, mozzarella, and marinara, repeating until the dish is full.',
    'Top with remaining mozzarella and parmesan, then cover with foil.',
    'Bake for 25 minutes covered and 15 minutes uncovered, then rest 10 minutes before slicing.'
  ),
  json_array('dinner', 'pasta', 'vegetarian', 'lasagna', 'baked', 'recipesaurus'),
  'https://commons.wikimedia.org/wiki/Special:FilePath/Vegetarian_lasagna_.jpg',
  'https://commons.wikimedia.org/wiki/File:Vegetarian_lasagna_.jpg',
  '30 mins',
  '40 mins',
  '8',
  1,
  1760000000022
),
(
  'recipesaurus-sample-023',
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  'Blueberry Muffins',
  'Tender bakery-style muffins packed with blueberries, lemon zest, vanilla, and a crunchy sugar top.',
  json_array(
    '2 cups all-purpose flour',
    '3/4 cup granulated sugar',
    '2 teaspoons baking powder',
    '1/2 teaspoon fine sea salt',
    '1 teaspoon lemon zest',
    '1 1/2 cups fresh or frozen blueberries',
    '2 large eggs',
    '1/2 cup whole milk',
    '1/2 cup unsalted butter, melted and cooled',
    '1/4 cup plain yogurt or sour cream',
    '1 teaspoon vanilla extract',
    '2 tablespoons turbinado sugar'
  ),
  json_array(
    'Heat oven to 375 F and line a 12-cup muffin tin with paper liners.',
    'Whisk flour, sugar, baking powder, salt, and lemon zest in a large bowl.',
    'Toss blueberries with 1 tablespoon of the flour mixture to help suspend them in the batter.',
    'Whisk eggs, milk, melted butter, yogurt, and vanilla in a second bowl.',
    'Fold wet ingredients into dry ingredients until just combined.',
    'Gently fold in the blueberries without overmixing.',
    'Divide batter among muffin cups and sprinkle with turbinado sugar.',
    'Bake for 20 to 24 minutes until the tops spring back and a toothpick comes out clean.'
  ),
  json_array('breakfast', 'baking', 'blueberries', 'muffins', 'make-ahead', 'recipesaurus'),
  'https://commons.wikimedia.org/wiki/Special:FilePath/Blueberry_muffins.jpg',
  'https://commons.wikimedia.org/wiki/File:Blueberry_muffins.jpg',
  '15 mins',
  '24 mins',
  '12',
  1,
  1760000000023
),
(
  'recipesaurus-sample-024',
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  'Spaghetti and Meatballs',
  'Juicy beef-pork meatballs simmered in marinara and served over spaghetti with parmesan and basil.',
  json_array(
    '12 ounces spaghetti',
    '1/2 pound ground beef',
    '1/2 pound ground pork',
    '1/2 cup breadcrumbs',
    '1/4 cup milk',
    '1 large egg',
    '2 garlic cloves, minced',
    '1/4 cup grated parmesan, plus more for serving',
    '2 tablespoons chopped parsley',
    '3 cups marinara sauce',
    '2 tablespoons olive oil',
    '1 teaspoon kosher salt',
    '1/2 teaspoon black pepper',
    'Fresh basil, for serving'
  ),
  json_array(
    'Soak breadcrumbs in milk for 5 minutes in a large bowl.',
    'Add beef, pork, egg, garlic, parmesan, parsley, salt, and pepper, then mix gently.',
    'Shape the mixture into 16 meatballs.',
    'Heat olive oil in a wide skillet and brown the meatballs on all sides.',
    'Pour marinara sauce into the skillet and simmer meatballs for 15 to 18 minutes until cooked through.',
    'Meanwhile, boil spaghetti in salted water until al dente.',
    'Drain spaghetti and toss with a spoonful of sauce.',
    'Serve pasta topped with meatballs, more sauce, parmesan, and basil.'
  ),
  json_array('dinner', 'pasta', 'meatballs', 'classic', 'comfort food', 'recipesaurus'),
  'https://commons.wikimedia.org/wiki/Special:FilePath/Spaghetti_and_meatballs.jpg',
  'https://commons.wikimedia.org/wiki/File:Spaghetti_and_meatballs.jpg',
  '25 mins',
  '30 mins',
  '4',
  1,
  1760000000024
),
(
  'recipesaurus-sample-025',
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  'Avocado Egg Toast',
  'Toasted sourdough topped with lemony avocado, jammy eggs, chives, pepper flakes, and olive oil.',
  json_array(
    '4 slices sourdough or whole-grain bread',
    '2 ripe avocados',
    '4 large eggs',
    '1 tablespoon fresh lemon juice',
    '1 tablespoon extra-virgin olive oil',
    '1/2 teaspoon kosher salt',
    '1/2 teaspoon freshly ground black pepper',
    '1/4 teaspoon red pepper flakes',
    '2 tablespoons chopped chives or cilantro',
    '1/2 cup cherry tomatoes, halved, optional',
    '1 teaspoon everything seasoning, optional'
  ),
  json_array(
    'Bring a small pot of water to a gentle boil.',
    'Lower eggs into the water and cook for 7 minutes for jammy yolks or 10 minutes for firm yolks.',
    'Transfer eggs to ice water, then peel and halve them.',
    'Toast bread until crisp at the edges but still tender in the center.',
    'Mash avocados with lemon juice, olive oil, salt, and black pepper.',
    'Spread avocado generously over each toast.',
    'Top with eggs, red pepper flakes, chives, tomatoes, and everything seasoning if using.',
    'Finish with a small drizzle of olive oil and serve right away.'
  ),
  json_array('breakfast', 'eggs', 'avocado', 'toast', 'quick', 'recipesaurus'),
  'https://commons.wikimedia.org/wiki/Special:FilePath/Avocado_and_Egg_Toast_(Unsplash).jpg',
  'https://commons.wikimedia.org/wiki/File:Avocado_and_Egg_Toast_(Unsplash).jpg',
  '10 mins',
  '10 mins',
  '4',
  1,
  1760000000025
);

INSERT OR REPLACE INTO recipes (
  id,
  user_id,
  owner_id,
  title,
  description,
  ingredients,
  instructions,
  tags,
  image_url,
  source_url,
  prep_time,
  cook_time,
  servings,
  is_public,
  created_at
) VALUES
(
  'recipesaurus-sample-026',
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  'Fresh Kimchi Geotjeori',
  'A quick napa cabbage kimchi tossed fresh with gochugaru, garlic, fish sauce, scallions, and sesame.',
  json_array(
    '1 medium napa cabbage, about 2 pounds',
    '1/4 cup coarse sea salt',
    '6 cups cold water for salting',
    '4 scallions, cut into 2-inch pieces',
    '1/2 small carrot, julienned',
    '4 garlic cloves, minced',
    '1 teaspoon grated fresh ginger',
    '1/3 cup gochugaru Korean pepper flakes',
    '2 tablespoons fish sauce or soup soy sauce',
    '1 tablespoon maesil syrup or sugar',
    '1 tablespoon rice vinegar, optional for brightness',
    '1 tablespoon toasted sesame seeds',
    '1 teaspoon toasted sesame oil'
  ),
  json_array(
    'Trim the napa cabbage and cut it into large bite-size pieces.',
    'Dissolve salt in cold water, add the cabbage, and toss so the leaves are evenly moistened.',
    'Let the cabbage stand for 35 to 45 minutes, turning once, until the thick ribs bend without snapping.',
    'Rinse the cabbage briefly, drain well, and pat away excess water.',
    'Mix garlic, ginger, gochugaru, fish sauce, maesil syrup, vinegar, sesame seeds, and sesame oil in a large bowl.',
    'Add cabbage, scallions, and carrot to the seasoning paste.',
    'Toss gently with gloved hands until every leaf is evenly coated.',
    'Taste and adjust with a pinch of salt or a little more syrup, then serve fresh or chill for later that day.'
  ),
  json_array('korean', 'kimchi', 'vegetarian-option', 'side dish', 'quick', 'recipesaurus'),
  'https://commons.wikimedia.org/wiki/Special:FilePath/Geotjeori.jpg',
  'https://seonkyounglongest.com/fresh-kimchi/',
  '50 mins',
  '0 mins',
  '6',
  1,
  1760000000026
),
(
  'recipesaurus-sample-027',
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  'Korean Braised Cod Daegu Jorim',
  'Tender cod simmered with radish, onion, scallions, and a savory gochugaru-soy braising sauce.',
  json_array(
    '1 1/2 pounds cod fillets or steaks',
    '10 ounces Korean radish or daikon, sliced 1/2 inch thick',
    '1/2 yellow onion, sliced',
    '2 scallions, cut into 2-inch pieces',
    '1 mild green chile, sliced, optional',
    '3 garlic cloves, minced',
    '1 teaspoon grated fresh ginger',
    '3 tablespoons soy sauce',
    '1 tablespoon fish sauce',
    '2 tablespoons gochugaru Korean pepper flakes',
    '1 tablespoon mirin or rice wine',
    '2 teaspoons sugar or rice syrup',
    '1 teaspoon toasted sesame oil',
    '1 cup anchovy kelp stock or water'
  ),
  json_array(
    'Pat the cod dry and check for any pin bones.',
    'Arrange radish slices in a shallow pot and pour in the stock.',
    'Mix garlic, ginger, soy sauce, fish sauce, gochugaru, mirin, sugar, and sesame oil in a bowl.',
    'Spoon half of the sauce over the radish and simmer for 8 minutes to start softening it.',
    'Place cod on top of the radish, then add onion, scallions, and chile.',
    'Spoon the remaining sauce over the fish.',
    'Simmer uncovered for 12 to 15 minutes, basting occasionally, until the cod flakes easily.',
    'Serve hot with steamed rice and extra braising liquid spooned over the top.'
  ),
  json_array('korean', 'seafood', 'cod', 'braised', 'dinner', 'recipesaurus'),
  'https://commons.wikimedia.org/wiki/Special:FilePath/Korean%20cuisine-Saengseon%20jorim-01.jpg',
  'https://seonkyounglongest.com/korean-braised-cod/',
  '15 mins',
  '25 mins',
  '4',
  1,
  1760000000027
),
(
  'recipesaurus-sample-028',
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  'Bulgogi Jeongol Beef Hot Pot',
  'A bubbling Korean beef hot pot with marinated bulgogi, mushrooms, glass noodles, tofu, and vegetables.',
  json_array(
    '1 pound thinly sliced ribeye or sirloin',
    '3 tablespoons soy sauce',
    '1 tablespoon brown sugar',
    '1 tablespoon grated Asian pear or apple',
    '3 garlic cloves, minced',
    '1 tablespoon toasted sesame oil',
    '1/2 teaspoon black pepper',
    '4 ounces sweet potato glass noodles, soaked',
    '4 cups beef broth or anchovy kelp stock',
    '8 ounces mushrooms, sliced or separated',
    '1/2 onion, sliced',
    '2 cups napa cabbage, chopped',
    '6 ounces firm tofu, sliced',
    '3 scallions, cut into 2-inch pieces'
  ),
  json_array(
    'Combine soy sauce, brown sugar, pear, garlic, sesame oil, and black pepper in a bowl.',
    'Add the sliced beef and marinate for at least 15 minutes.',
    'Arrange mushrooms, onion, cabbage, tofu, scallions, and soaked glass noodles in a wide pot.',
    'Place the marinated beef in the center of the vegetables.',
    'Pour broth around the edges of the pot without washing seasoning off the beef.',
    'Bring to a lively simmer over medium-high heat.',
    'Cook for 10 to 12 minutes, gently separating the beef slices as they cook.',
    'Serve at the table with rice, adding more broth if the noodles absorb too much liquid.'
  ),
  json_array('korean', 'beef', 'hot pot', 'bulgogi', 'dinner', 'recipesaurus'),
  'https://commons.wikimedia.org/wiki/Special:FilePath/Bulgogi-jeongol%201.jpg',
  'https://seonkyounglongest.com/korean-beef-hot-pot/',
  '25 mins',
  '15 mins',
  '4',
  1,
  1760000000028
),
(
  'recipesaurus-sample-029',
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  'Donkkaseu Korean Pork Cutlet',
  'Crisp panko-coated pork cutlets served with cabbage, rice, and a glossy sweet-savory cutlet sauce.',
  json_array(
    '4 boneless pork loin chops, about 1/2 inch thick',
    '1 teaspoon kosher salt',
    '1/2 teaspoon black pepper',
    '1/2 cup all-purpose flour',
    '2 large eggs, beaten',
    '2 cups panko breadcrumbs',
    'Neutral oil for shallow frying',
    '2 tablespoons unsalted butter',
    '2 tablespoons all-purpose flour for sauce',
    '1 cup chicken or beef stock',
    '2 tablespoons ketchup',
    '1 tablespoon Worcestershire sauce',
    '1 tablespoon soy sauce',
    '2 teaspoons sugar',
    'Shredded cabbage and steamed rice for serving'
  ),
  json_array(
    'Pound the pork chops to an even 1/4-inch thickness and season both sides with salt and pepper.',
    'Set up three shallow dishes with flour, beaten eggs, and panko.',
    'Dredge each pork piece in flour, dip in egg, and press firmly into panko.',
    'Rest the breaded cutlets for 10 minutes so the coating hydrates.',
    'Melt butter in a small saucepan, whisk in flour, and cook for 1 minute.',
    'Whisk in stock, ketchup, Worcestershire, soy sauce, and sugar, then simmer until glossy.',
    'Fry cutlets in 350 F oil for 3 to 4 minutes per side until deep golden and cooked through.',
    'Slice and serve with sauce, shredded cabbage, and steamed rice.'
  ),
  json_array('korean', 'pork', 'cutlet', 'fried', 'dinner', 'recipesaurus'),
  'https://commons.wikimedia.org/wiki/Special:FilePath/Pork-cutlet.jpg',
  'https://seonkyounglongest.com/donkkaseu/',
  '25 mins',
  '20 mins',
  '4',
  1,
  1760000000029
),
(
  'recipesaurus-sample-030',
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  'Jjampong Spicy Seafood Noodle Soup',
  'A fiery Korean-Chinese noodle soup with seafood, vegetables, garlic, ginger, and a gochugaru broth.',
  json_array(
    '12 ounces fresh wheat noodles or udon noodles',
    '6 ounces shrimp, peeled and deveined',
    '6 ounces squid, cleaned and sliced',
    '8 mussels or clams, scrubbed',
    '2 tablespoons neutral oil',
    '3 garlic cloves, minced',
    '1 tablespoon minced fresh ginger',
    '1/2 onion, sliced',
    '2 cups napa cabbage, sliced',
    '1 small zucchini, sliced',
    '1 carrot, thinly sliced',
    '3 tablespoons gochugaru Korean pepper flakes',
    '1 tablespoon soy sauce',
    '5 cups chicken stock or seafood stock',
    '2 scallions, sliced'
  ),
  json_array(
    'Cook noodles until just tender, rinse briefly, and divide among serving bowls.',
    'Heat oil in a wok or soup pot over medium-high heat.',
    'Stir-fry garlic, ginger, onion, cabbage, zucchini, and carrot for 3 minutes.',
    'Add gochugaru and soy sauce, stirring constantly so the pepper flakes bloom without burning.',
    'Pour in stock and bring the broth to a strong simmer.',
    'Add shrimp, squid, and mussels or clams.',
    'Cook for 3 to 5 minutes until the shellfish open and the shrimp are pink.',
    'Ladle hot soup over the noodles and finish with scallions.'
  ),
  json_array('korean', 'seafood', 'noodles', 'soup', 'spicy', 'recipesaurus'),
  'https://commons.wikimedia.org/wiki/Special:FilePath/Jjamppong%20(Korean%20Chines%20seafood%20noodle%20soup).jpg',
  'https://seonkyounglongest.com/jjamppong/',
  '25 mins',
  '20 mins',
  '4',
  1,
  1760000000030
),
(
  'recipesaurus-sample-031',
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  'Bibimmyeon Cold Spicy Noodles',
  'Chilled noodles tossed in a tangy gochujang sauce with cucumber, kimchi, sesame, and a jammy egg.',
  json_array(
    '12 ounces thin wheat noodles, somyeon, or ramen noodles',
    '1/3 cup gochujang',
    '1 tablespoon gochugaru Korean pepper flakes',
    '2 tablespoons rice vinegar',
    '1 tablespoon soy sauce',
    '1 tablespoon sugar or maesil syrup',
    '1 tablespoon toasted sesame oil',
    '1 garlic clove, finely grated',
    '1 cup cucumber, julienned',
    '1 cup chopped kimchi',
    '2 soft-boiled eggs, halved',
    '2 scallions, thinly sliced',
    '1 tablespoon toasted sesame seeds',
    'Roasted seaweed strips, optional'
  ),
  json_array(
    'Whisk gochujang, gochugaru, vinegar, soy sauce, sugar, sesame oil, and garlic in a mixing bowl.',
    'Cook noodles according to package directions until springy but tender.',
    'Drain the noodles and rinse under cold running water until completely chilled.',
    'Rub the noodles lightly between your hands while rinsing to remove excess starch.',
    'Drain very well so the sauce stays bold and clingy.',
    'Toss noodles with the spicy sauce until evenly coated.',
    'Add cucumber, kimchi, scallions, sesame seeds, and seaweed if using.',
    'Divide among bowls and top each serving with a soft-boiled egg.'
  ),
  json_array('korean', 'noodles', 'cold', 'spicy', 'quick', 'recipesaurus'),
  'https://commons.wikimedia.org/wiki/Special:FilePath/Korean%20noodles-Bibim%20guksu-01.jpg',
  'https://seonkyounglongest.com/bibimmyeon/',
  '15 mins',
  '8 mins',
  '4',
  1,
  1760000000031
),
(
  'recipesaurus-sample-032',
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  'Kkanpunggi Spicy Garlic Fried Chicken',
  'Crispy bite-size chicken tossed with garlic, dried chiles, scallions, and a sticky sweet-sour soy glaze.',
  json_array(
    '1 1/2 pounds boneless chicken thighs, cut into bite-size pieces',
    '1/2 teaspoon kosher salt',
    '1/2 teaspoon black pepper',
    '1 tablespoon rice wine or mirin',
    '1 large egg white',
    '3/4 cup potato starch',
    'Neutral oil for frying',
    '5 garlic cloves, thinly sliced',
    '1 tablespoon minced fresh ginger',
    '4 dried red chiles, cut into pieces',
    '3 scallions, sliced',
    '3 tablespoons soy sauce',
    '2 tablespoons rice vinegar',
    '2 tablespoons sugar',
    '1 teaspoon gochugaru Korean pepper flakes'
  ),
  json_array(
    'Season chicken with salt, pepper, and rice wine, then let it stand for 10 minutes.',
    'Mix in egg white, then coat the chicken pieces thoroughly with potato starch.',
    'Heat oil to 350 F in a deep skillet or pot.',
    'Fry chicken in batches for 4 to 5 minutes until pale golden and cooked through.',
    'Raise the oil heat slightly and fry the chicken a second time for 1 to 2 minutes until very crisp.',
    'Stir-fry garlic, ginger, dried chiles, and scallions in a clean pan for 30 seconds.',
    'Add soy sauce, vinegar, sugar, and gochugaru, simmering until syrupy.',
    'Toss the fried chicken in the glaze and serve immediately.'
  ),
  json_array('korean', 'chicken', 'fried', 'spicy', 'dinner', 'recipesaurus'),
  'https://commons.wikimedia.org/wiki/Special:FilePath/Korean%20cuisine-Kkanpunggi-01.jpg',
  'https://seonkyounglongest.com/kkanpunggi/',
  '25 mins',
  '25 mins',
  '4',
  1,
  1760000000032
),
(
  'recipesaurus-sample-033',
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  'Jjimdak Soy Braised Chicken',
  'A glossy Korean braised chicken with potatoes, carrots, glass noodles, chiles, and a garlicky soy sauce.',
  json_array(
    '2 pounds bone-in chicken thighs or drumsticks',
    '4 ounces sweet potato glass noodles, soaked',
    '2 medium potatoes, cut into chunks',
    '1 carrot, cut into chunks',
    '1 onion, sliced',
    '3 scallions, cut into 2-inch pieces',
    '4 dried red chiles or 1 fresh chile, optional',
    '1/2 cup soy sauce',
    '2 tablespoons oyster sauce',
    '2 tablespoons brown sugar',
    '2 tablespoons mirin or rice wine',
    '5 garlic cloves, minced',
    '1 tablespoon grated fresh ginger',
    '2 cups water or chicken stock',
    '1 tablespoon toasted sesame oil'
  ),
  json_array(
    'Blanch chicken in boiling water for 3 minutes, then drain and rinse to keep the sauce clean.',
    'Combine soy sauce, oyster sauce, brown sugar, mirin, garlic, ginger, and water in a wide pot.',
    'Add chicken and bring the liquid to a boil.',
    'Reduce to a simmer, cover partially, and cook for 15 minutes.',
    'Add potatoes, carrot, onion, and chiles, then simmer for 15 minutes more.',
    'Add soaked glass noodles and scallions, pressing them into the sauce.',
    'Cook uncovered for 6 to 8 minutes until the noodles are tender and the sauce is glossy.',
    'Finish with sesame oil and serve with steamed rice.'
  ),
  json_array('korean', 'chicken', 'braised', 'noodles', 'dinner', 'recipesaurus'),
  'https://commons.wikimedia.org/wiki/Special:FilePath/Korean%20cuisine-Andong%20jjimdak-01.jpg',
  'https://seonkyounglongest.com/jjimdak-korean-braised-chicken/',
  '25 mins',
  '45 mins',
  '4',
  1,
  1760000000033
),
(
  'recipesaurus-sample-034',
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  'Spicy Garlic Eggplant Muchim',
  'Soft eggplant pieces dressed with soy, garlic, gochugaru, scallions, sesame oil, and toasted sesame seeds.',
  json_array(
    '4 small Japanese or Korean eggplants',
    '1/2 teaspoon kosher salt',
    '2 tablespoons soy sauce',
    '1 tablespoon rice vinegar',
    '1 tablespoon toasted sesame oil',
    '2 garlic cloves, finely grated',
    '1 tablespoon gochugaru Korean pepper flakes',
    '1 teaspoon sugar or maesil syrup',
    '2 scallions, finely sliced',
    '1 tablespoon toasted sesame seeds',
    '1 teaspoon fish sauce or soup soy sauce, optional',
    '1 small chile, thinly sliced, optional'
  ),
  json_array(
    'Trim the eggplants and cut them into 3-inch batons or thick wedges.',
    'Steam the eggplant for 5 to 7 minutes until tender but not collapsing.',
    'Spread the eggplant on a plate and let it cool until easy to handle.',
    'Gently squeeze out excess moisture without crushing the pieces.',
    'Whisk soy sauce, vinegar, sesame oil, garlic, gochugaru, sugar, and fish sauce if using.',
    'Add eggplant, scallions, sesame seeds, and sliced chile to the dressing.',
    'Toss gently so the eggplant stays intact while absorbing the seasoning.',
    'Serve at room temperature as banchan, or chill for up to 1 day.'
  ),
  json_array('korean', 'eggplant', 'vegan-option', 'side dish', 'spicy', 'recipesaurus'),
  'https://commons.wikimedia.org/wiki/Special:FilePath/Gajibokkeum.jpg',
  'https://seonkyounglongest.com/korean-spicy-garlic-eggplant/',
  '15 mins',
  '7 mins',
  '4',
  1,
  1760000000034
),
(
  'recipesaurus-sample-035',
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  (SELECT id FROM users WHERE email = 'recipesaurus@recipesaurus.ai'),
  'Haemul Pajeon Seafood Pancake',
  'A crisp-edged Korean scallion pancake loaded with shrimp, squid, and tender green onions.',
  json_array(
    '1 bunch scallions, trimmed',
    '4 ounces shrimp, peeled and chopped',
    '4 ounces squid, cleaned and sliced',
    '1/2 cup chopped clams or mussels, optional',
    '3/4 cup all-purpose flour',
    '1/4 cup rice flour or potato starch',
    '1 large egg',
    '3/4 cup ice-cold water',
    '1/2 teaspoon kosher salt',
    '1/4 teaspoon black pepper',
    '3 tablespoons neutral oil, divided',
    '2 tablespoons soy sauce for dipping',
    '1 tablespoon rice vinegar for dipping',
    '1 teaspoon toasted sesame seeds'
  ),
  json_array(
    'Cut scallions to fit a 10-inch skillet and pat seafood very dry.',
    'Whisk flour, rice flour or potato starch, egg, cold water, salt, and pepper into a loose batter.',
    'Fold the seafood into the batter, keeping the scallions separate.',
    'Heat 2 tablespoons oil in a nonstick skillet over medium-high heat.',
    'Lay scallions in the skillet in an even layer, then pour seafood batter over and between them.',
    'Cook for 4 to 5 minutes until the underside is deep golden and crisp.',
    'Flip carefully, add remaining oil around the edge, and cook 4 minutes more.',
    'Mix soy sauce, vinegar, and sesame seeds for dipping, then slice the pancake and serve hot.'
  ),
  json_array('korean', 'seafood', 'pancake', 'scallions', 'appetizer', 'recipesaurus'),
  'https://commons.wikimedia.org/wiki/Special:FilePath/Korean%20pancake-Haemul%20pajeon-01.jpg',
  'https://seonkyounglongest.com/pajeon-korean-seafood-pancake/',
  '20 mins',
  '12 mins',
  '4',
  1,
  1760000000035
);
