import { useState } from 'react';
import { Link2, Download, Share2, Loader2, ChefHat, ArrowRight, Sparkles, Users, Book } from 'lucide-react';
import { DinoMascot } from './DinoMascot';
import { fetchAndExtractRecipe, ExtractedRecipeData } from '../utils/recipeExtractor';

interface ExtractedRecipe {
  title: string;
  description: string;
  ingredients: string[];
  instructions: string[];
  prepTime?: string;
  cookTime?: string;
  servings?: string;
  imageUrl?: string;
  sourceUrl: string;
}

interface PublicHomePageProps {
  onSignUp: () => void;
  onSignIn: () => void;
}

export function PublicHomePage({ onSignUp, onSignIn }: PublicHomePageProps) {
  const [url, setUrl] = useState('');
  const [isExtracting, setIsExtracting] = useState(false);
  const [extractedRecipe, setExtractedRecipe] = useState<ExtractedRecipe | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [shareLink, setShareLink] = useState<string | null>(null);

  const handleExtract = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!url.trim()) return;

    setIsExtracting(true);
    setError(null);
    setExtractedRecipe(null);
    setShareLink(null);

    try {
      const extracted = await fetchAndExtractRecipe(url.trim());

      // Convert to ExtractedRecipe format
      const recipe: ExtractedRecipe = {
        title: extracted.title || 'Untitled Recipe',
        description: extracted.description || '',
        ingredients: extracted.ingredients || [],
        instructions: extracted.instructions || [],
        prepTime: extracted.prepTime,
        cookTime: extracted.cookTime,
        servings: extracted.servings,
        imageUrl: extracted.imageUrl,
        sourceUrl: extracted.sourceUrl,
      };

      // Validate that we got meaningful data
      if (!recipe.title && !recipe.ingredients.length && !recipe.instructions.length) {
        throw new Error('Could not find recipe data on this page. Try a different URL.');
      }

      setExtractedRecipe(recipe);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to extract recipe. Please check the URL and try again.');
    } finally {
      setIsExtracting(false);
    }
  };

  const handleDownloadPDF = () => {
    if (!extractedRecipe) return;

    // Create a simple text-based PDF content
    const content = `
${extractedRecipe.title}

${extractedRecipe.description}

Prep Time: ${extractedRecipe.prepTime || 'N/A'}
Cook Time: ${extractedRecipe.cookTime || 'N/A'}
Servings: ${extractedRecipe.servings || 'N/A'}

INGREDIENTS:
${extractedRecipe.ingredients.map(i => `- ${i}`).join('\n')}

INSTRUCTIONS:
${extractedRecipe.instructions.map((s, i) => `${i + 1}. ${s}`).join('\n')}

Source: ${extractedRecipe.sourceUrl}

---
Generated by Recipesaurus
    `.trim();

    // Create and download as text file (in production, use a PDF library)
    const blob = new Blob([content], { type: 'text/plain' });
    const downloadUrl = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = downloadUrl;
    a.download = `${extractedRecipe.title.replace(/[^a-z0-9]/gi, '_')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(downloadUrl);
  };

  const handleShareLink = () => {
    if (!extractedRecipe) return;

    // Generate a shareable link (in production, this would create a server-side link)
    const mockShareId = btoa(extractedRecipe.sourceUrl).slice(0, 12);
    const link = `${window.location.origin}/preview/${mockShareId}`;
    setShareLink(link);

    // Copy to clipboard
    navigator.clipboard.writeText(link).catch(() => {});
  };

  return (
    <div className="public-home">
      {/* Hero Section */}
      <section className="hero-section">
        <div className="hero-content">
          <DinoMascot size={100} className="hero-mascot" />
          <h1>Save Recipes from Anywhere</h1>
          <p className="hero-subtitle">
            Paste any recipe URL and instantly extract, save, and organize your favorite recipes.
            No more scattered bookmarks or lost recipes.
          </p>

          {/* URL Extraction Form */}
          <form className="url-extract-form" onSubmit={handleExtract}>
            <div className="url-input-wrapper">
              <Link2 size={20} />
              <input
                type="url"
                value={url}
                onChange={(e) => setUrl(e.target.value)}
                placeholder="Paste a recipe URL..."
                required
              />
              <button
                type="submit"
                className="extract-btn"
                disabled={isExtracting || !url.trim()}
              >
                {isExtracting ? (
                  <Loader2 size={18} className="spin" />
                ) : (
                  <>
                    <Sparkles size={18} />
                    Extract
                  </>
                )}
              </button>
            </div>
          </form>

          {error && (
            <p className="extract-error">{error}</p>
          )}
        </div>
      </section>

      {/* Extracted Recipe Preview */}
      {extractedRecipe && (
        <section className="extracted-preview">
          <div className="preview-card">
            <div className="preview-header">
              <ChefHat size={24} />
              <h2>{extractedRecipe.title}</h2>
            </div>

            <p className="preview-description">{extractedRecipe.description}</p>

            <div className="preview-meta">
              {extractedRecipe.prepTime && (
                <span>Prep: {extractedRecipe.prepTime}</span>
              )}
              {extractedRecipe.cookTime && (
                <span>Cook: {extractedRecipe.cookTime}</span>
              )}
              {extractedRecipe.servings && (
                <span>Serves: {extractedRecipe.servings}</span>
              )}
            </div>

            <div className="preview-sections">
              <div className="preview-section">
                <h4>Ingredients</h4>
                <ul>
                  {extractedRecipe.ingredients.slice(0, 5).map((ing, i) => (
                    <li key={i}>{ing}</li>
                  ))}
                  {extractedRecipe.ingredients.length > 5 && (
                    <li className="more">+{extractedRecipe.ingredients.length - 5} more...</li>
                  )}
                </ul>
              </div>

              <div className="preview-section">
                <h4>Instructions</h4>
                <ol>
                  {extractedRecipe.instructions.slice(0, 3).map((step, i) => (
                    <li key={i}>{step}</li>
                  ))}
                  {extractedRecipe.instructions.length > 3 && (
                    <li className="more">+{extractedRecipe.instructions.length - 3} more steps...</li>
                  )}
                </ol>
              </div>
            </div>

            <div className="preview-actions">
              <button className="btn-secondary" onClick={handleDownloadPDF}>
                <Download size={16} />
                Download
              </button>
              <button className="btn-secondary" onClick={handleShareLink}>
                <Share2 size={16} />
                Share Link
              </button>
              <button className="btn-primary" onClick={onSignUp}>
                <ArrowRight size={16} />
                Save to Collection
              </button>
            </div>

            {shareLink && (
              <div className="share-link-result">
                <input type="text" value={shareLink} readOnly />
                <span>Link copied!</span>
              </div>
            )}
          </div>

          <div className="signup-prompt">
            <h3>Want to save this recipe?</h3>
            <p>Create a free account to save, organize, and share your recipes.</p>
            <div className="prompt-actions">
              <button className="btn-primary btn-lg" onClick={onSignUp}>
                Get Started Free
              </button>
              <button className="btn-text" onClick={onSignIn}>
                Already have an account? Sign In
              </button>
            </div>
          </div>
        </section>
      )}

      {/* Features Section */}
      <section className="features-section">
        <h2>Why Recipesaurus?</h2>
        <div className="features-grid">
          <div className="feature-card">
            <div className="feature-icon">
              <Link2 size={28} />
            </div>
            <h3>Extract from Any URL</h3>
            <p>Paste a link from your favorite food blog or website and we'll extract the recipe automatically.</p>
          </div>

          <div className="feature-card">
            <div className="feature-icon">
              <Book size={28} />
            </div>
            <h3>Organize in Cookbooks</h3>
            <p>Create collections to organize your recipes by cuisine, occasion, or however you like.</p>
          </div>

          <div className="feature-card">
            <div className="feature-icon">
              <Users size={28} />
            </div>
            <h3>Share with Friends</h3>
            <p>Share cookbooks with family and friends. Collaborate on meal planning together.</p>
          </div>

          <div className="feature-card">
            <div className="feature-icon">
              <Sparkles size={28} />
            </div>
            <h3>Discover New Recipes</h3>
            <p>Explore public recipes shared by our community and save your favorites.</p>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="cta-section">
        <DinoMascot size={80} />
        <h2>Ready to organize your recipes?</h2>
        <p>Join thousands of home cooks who use Recipesaurus to save and share their favorite recipes.</p>
        <div className="cta-actions">
          <button className="btn-primary btn-lg" onClick={onSignUp}>
            Get Started Free
          </button>
          <button className="btn-secondary btn-lg" onClick={onSignIn}>
            Sign In
          </button>
        </div>
      </section>
    </div>
  );
}
