import { useState } from 'react';
import { Link2, Download, Share2, Loader2, ChefHat, ArrowRight, Sparkles, Users, Book } from 'lucide-react';
import { DinoMascot } from './DinoMascot';
import { fetchAndExtractRecipe } from '../utils/recipeExtractor';
import { jsPDF } from 'jspdf';
import { compressToEncodedURIComponent } from 'lz-string';

interface ExtractedRecipe {
  title: string;
  description: string;
  ingredients: string[];
  instructions: string[];
  prepTime?: string;
  cookTime?: string;
  servings?: string;
  imageUrl?: string;
  sourceUrl: string;
}

interface PublicHomePageProps {
  onSignUp: () => void;
  onSignIn: () => void;
}

export function PublicHomePage({ onSignUp, onSignIn }: PublicHomePageProps) {
  const [url, setUrl] = useState('');
  const [isExtracting, setIsExtracting] = useState(false);
  const [extractedRecipe, setExtractedRecipe] = useState<ExtractedRecipe | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [shareLink, setShareLink] = useState<string | null>(null);

  const handleExtract = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!url.trim()) return;

    setIsExtracting(true);
    setError(null);
    setExtractedRecipe(null);
    setShareLink(null);

    try {
      const extracted = await fetchAndExtractRecipe(url.trim());

      // Convert to ExtractedRecipe format
      const recipe: ExtractedRecipe = {
        title: extracted.title || 'Untitled Recipe',
        description: extracted.description || '',
        ingredients: extracted.ingredients || [],
        instructions: extracted.instructions || [],
        prepTime: extracted.prepTime,
        cookTime: extracted.cookTime,
        servings: extracted.servings,
        imageUrl: extracted.imageUrl,
        sourceUrl: extracted.sourceUrl,
      };

      // Validate that we got meaningful data
      if (!recipe.title && !recipe.ingredients.length && !recipe.instructions.length) {
        throw new Error('Could not find recipe data on this page. Try a different URL.');
      }

      setExtractedRecipe(recipe);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to extract recipe. Please check the URL and try again.');
    } finally {
      setIsExtracting(false);
    }
  };

  const handleDownloadPDF = () => {
    if (!extractedRecipe) return;

    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const maxWidth = pageWidth - margin * 2;
    let yPos = 20;

    // Title
    doc.setFontSize(24);
    doc.setFont('helvetica', 'bold');
    const titleLines = doc.splitTextToSize(extractedRecipe.title, maxWidth);
    doc.text(titleLines, margin, yPos);
    yPos += titleLines.length * 10 + 5;

    // Description
    if (extractedRecipe.description) {
      doc.setFontSize(12);
      doc.setFont('helvetica', 'normal');
      doc.setTextColor(100);
      const descLines = doc.splitTextToSize(extractedRecipe.description, maxWidth);
      doc.text(descLines, margin, yPos);
      yPos += descLines.length * 6 + 10;
    }

    // Meta info
    doc.setTextColor(0);
    doc.setFontSize(10);
    const meta = [];
    if (extractedRecipe.prepTime) meta.push(`Prep: ${extractedRecipe.prepTime}`);
    if (extractedRecipe.cookTime) meta.push(`Cook: ${extractedRecipe.cookTime}`);
    if (extractedRecipe.servings) meta.push(`Servings: ${extractedRecipe.servings}`);
    if (meta.length > 0) {
      doc.text(meta.join('  |  '), margin, yPos);
      yPos += 15;
    }

    // Ingredients
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Ingredients', margin, yPos);
    yPos += 8;

    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    extractedRecipe.ingredients.forEach(ing => {
      if (yPos > 270) {
        doc.addPage();
        yPos = 20;
      }
      const lines = doc.splitTextToSize(`• ${ing}`, maxWidth);
      doc.text(lines, margin, yPos);
      yPos += lines.length * 5 + 2;
    });

    yPos += 10;

    // Instructions
    if (yPos > 250) {
      doc.addPage();
      yPos = 20;
    }
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Instructions', margin, yPos);
    yPos += 8;

    doc.setFontSize(11);
    doc.setFont('helvetica', 'normal');
    extractedRecipe.instructions.forEach((step, i) => {
      if (yPos > 270) {
        doc.addPage();
        yPos = 20;
      }
      const lines = doc.splitTextToSize(`${i + 1}. ${step}`, maxWidth);
      doc.text(lines, margin, yPos);
      yPos += lines.length * 5 + 4;
    });

    // Source
    yPos += 10;
    if (yPos > 280) {
      doc.addPage();
      yPos = 20;
    }
    doc.setFontSize(9);
    doc.setTextColor(100);
    doc.text(`Source: ${extractedRecipe.sourceUrl}`, margin, yPos);
    yPos += 10;
    doc.text('Generated by Recipesaurus', margin, yPos);

    // Download
    const filename = extractedRecipe.title.replace(/[^a-z0-9]/gi, '_').substring(0, 50);
    doc.save(`${filename}_Recipe.pdf`);
  };

  const handleShareLink = () => {
    if (!extractedRecipe) return;

    // Compress recipe data and encode in URL
    const recipeData = JSON.stringify(extractedRecipe);
    const compressed = compressToEncodedURIComponent(recipeData);
    const link = `${window.location.origin}/preview/${compressed}`;
    setShareLink(link);

    // Copy to clipboard
    navigator.clipboard.writeText(link).catch(() => {});
  };

  return (
    <div className="public-home">
      {/* Hero Section */}
      <section className="hero-section">
        <div className="hero-content">
          <DinoMascot size={100} className="hero-mascot" />
          <h1>Save Recipes from Anywhere</h1>
          <p className="hero-subtitle">
            Paste any recipe URL and instantly extract, save, and organize your favorite recipes.
            No more scattered bookmarks or lost recipes.
          </p>

          {/* URL Extraction Form */}
          <form className="url-extract-form" onSubmit={handleExtract}>
            <div className="url-input-wrapper">
              <Link2 size={20} />
              <input
                type="url"
                value={url}
                onChange={(e) => setUrl(e.target.value)}
                placeholder="Paste a recipe URL..."
                required
              />
              <button
                type="submit"
                className="extract-btn"
                disabled={isExtracting || !url.trim()}
              >
                {isExtracting ? (
                  <Loader2 size={18} className="spin" />
                ) : (
                  <>
                    <Sparkles size={18} />
                    Extract
                  </>
                )}
              </button>
            </div>
          </form>

          {error && (
            <p className="extract-error">{error}</p>
          )}
        </div>
      </section>

      {/* Extracted Recipe Preview */}
      {extractedRecipe && (
        <section className="extracted-preview">
          <div className="preview-card">
            <div className="preview-header">
              <ChefHat size={24} />
              <h2>{extractedRecipe.title}</h2>
            </div>

            <p className="preview-description">{extractedRecipe.description}</p>

            <div className="preview-meta">
              {extractedRecipe.prepTime && (
                <span>Prep: {extractedRecipe.prepTime}</span>
              )}
              {extractedRecipe.cookTime && (
                <span>Cook: {extractedRecipe.cookTime}</span>
              )}
              {extractedRecipe.servings && (
                <span>Serves: {extractedRecipe.servings}</span>
              )}
            </div>

            <div className="preview-sections">
              <div className="preview-section">
                <h4>Ingredients</h4>
                <ul>
                  {extractedRecipe.ingredients.slice(0, 5).map((ing, i) => (
                    <li key={i}>{ing}</li>
                  ))}
                  {extractedRecipe.ingredients.length > 5 && (
                    <li className="more">+{extractedRecipe.ingredients.length - 5} more...</li>
                  )}
                </ul>
              </div>

              <div className="preview-section">
                <h4>Instructions</h4>
                <ol>
                  {extractedRecipe.instructions.slice(0, 3).map((step, i) => (
                    <li key={i}>{step}</li>
                  ))}
                  {extractedRecipe.instructions.length > 3 && (
                    <li className="more">+{extractedRecipe.instructions.length - 3} more steps...</li>
                  )}
                </ol>
              </div>
            </div>

            <div className="preview-actions">
              <button className="btn-secondary" onClick={handleDownloadPDF}>
                <Download size={16} />
                Download
              </button>
              <button className="btn-secondary" onClick={handleShareLink}>
                <Share2 size={16} />
                Share Link
              </button>
              <button className="btn-primary" onClick={onSignUp}>
                <ArrowRight size={16} />
                Save to Collection
              </button>
            </div>

            {shareLink && (
              <div className="share-link-result">
                <input type="text" value={shareLink} readOnly />
                <span>Link copied!</span>
              </div>
            )}
          </div>

          <div className="signup-prompt">
            <h3>Want to save this recipe?</h3>
            <p>Create a free account to save, organize, and share your recipes.</p>
            <div className="prompt-actions">
              <button className="btn-primary btn-lg" onClick={onSignUp}>
                Get Started Free
              </button>
              <button className="btn-text" onClick={onSignIn}>
                Already have an account? Sign In
              </button>
            </div>
          </div>
        </section>
      )}

      {/* Features Section */}
      <section className="features-section">
        <h2>Why Recipesaurus?</h2>
        <div className="features-grid">
          <div className="feature-card">
            <div className="feature-icon">
              <Link2 size={28} />
            </div>
            <h3>Extract from Any URL</h3>
            <p>Paste a link from your favorite food blog or website and we'll extract the recipe automatically.</p>
          </div>

          <div className="feature-card">
            <div className="feature-icon">
              <Book size={28} />
            </div>
            <h3>Organize in Cookbooks</h3>
            <p>Create collections to organize your recipes by cuisine, occasion, or however you like.</p>
          </div>

          <div className="feature-card">
            <div className="feature-icon">
              <Users size={28} />
            </div>
            <h3>Share with Friends</h3>
            <p>Share cookbooks with family and friends. Collaborate on meal planning together.</p>
          </div>

          <div className="feature-card">
            <div className="feature-icon">
              <Sparkles size={28} />
            </div>
            <h3>Discover New Recipes</h3>
            <p>Explore public recipes shared by our community and save your favorites.</p>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="cta-section">
        <DinoMascot size={80} />
        <h2>Ready to organize your recipes?</h2>
        <p>Join thousands of home cooks who use Recipesaurus to save and share their favorite recipes.</p>
        <div className="cta-actions">
          <button className="btn-primary btn-lg" onClick={onSignUp}>
            Get Started Free
          </button>
          <button className="btn-secondary btn-lg" onClick={onSignIn}>
            Sign In
          </button>
        </div>
      </section>
    </div>
  );
}
