import { jsPDF } from 'jspdf';

export interface RecipePdfData {
  title: string;
  description?: string | null;
  ingredients: string[];
  instructions: string[];
  prepTime?: string | null;
  cookTime?: string | null;
  servings?: string | null;
  sourceUrl?: string | null;
}

function getRecipePdfFilename(title: string): string {
  const filename = title.replace(/[^a-z0-9]/gi, '_').replace(/^_+|_+$/g, '').substring(0, 50);
  return `${filename || 'Recipe'}_Recipe.pdf`;
}

export function downloadRecipePdf(recipe: RecipePdfData): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const bottomMargin = 20;
  const maxWidth = pageWidth - margin * 2;
  let yPos = 20;

  const ensureSpace = (needed = 0) => {
    if (yPos + needed > pageHeight - bottomMargin) {
      doc.addPage();
      yPos = 20;
    }
  };

  const addWrappedText = (text: string, lineHeight: number, gap = 0) => {
    const lines = doc.splitTextToSize(text, maxWidth);
    const textLines = Array.isArray(lines) ? lines : [lines];
    textLines.forEach(line => {
      ensureSpace(lineHeight);
      doc.text(line, margin, yPos);
      yPos += lineHeight;
    });
    yPos += gap;
  };

  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  addWrappedText(recipe.title, 10, 5);

  if (recipe.description) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100);
    addWrappedText(recipe.description, 6, 10);
  }

  doc.setTextColor(0);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const meta = [];
  if (recipe.prepTime) meta.push(`Prep: ${recipe.prepTime}`);
  if (recipe.cookTime) meta.push(`Cook: ${recipe.cookTime}`);
  if (recipe.servings) meta.push(`Servings: ${recipe.servings}`);
  if (meta.length > 0) {
    addWrappedText(meta.join('  |  '), 5, 10);
  }

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  addWrappedText('Ingredients', 8, 0);

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  recipe.ingredients.forEach(ingredient => {
    addWrappedText(`- ${ingredient}`, 5, 2);
  });

  yPos += 8;

  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  addWrappedText('Instructions', 8, 0);

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  recipe.instructions.forEach((step, index) => {
    addWrappedText(`${index + 1}. ${step}`, 5, 4);
  });

  yPos += 10;
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100);

  if (recipe.sourceUrl) {
    addWrappedText(`Source: ${recipe.sourceUrl}`, 5, 5);
  }

  addWrappedText('Generated by Recipesaurus', 5);
  doc.save(getRecipePdfFilename(recipe.title));
}
